FROM jenkins/inbound-agent:latest
USER root
#Install necessary packages
RUN apt-get update && apt-get install -y wget unzip python3 python3-pip nodejs npm redis-server && npm install -g npm && rm -rf /var/lib/apt/lists/*
#Install Terraform
ARG TERRAFORM_VERSION=1.1.5
RUN wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && unzip /tmp/terraform.zip -d /usr/local/bin && rm /tmp/terraform.zip
USER jenkins
#Set default working directory for Jenkins agent
WORKDIR /home/jenkins
#Expose ports for Redis
EXPOSE 6379
CMD ["bash"]