FROM jenkins/inbound-agent:latest

USER root

# Install necessary packages
RUN apt-get update && apt-get install -y wget unzip python3 python3-pip nodejs npm redis-server && npm install -g npm && rm -rf /var/lib/apt/lists/*

# Install Terraform
ARG TERRAFORM_VERSION=1.1.5
RUN wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip /tmp/terraform.zip -d /usr/local/bin && \
    rm /tmp/terraform.zip

# Copy AWS credentials to a temporary file
ARG AWS_CREDENTIALS_FILE
COPY $AWS_CREDENTIALS_FILE /tmp/aws-credentials

# Install AWS CLI and configure credentials
RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip && \
    source /tmp/aws-credentials && \
    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

USER jenkins

# Set default working directory for Jenkins agent
WORKDIR /home/jenkins

# Expose ports for Redis
EXPOSE 6379

CMD ["bash"]
